# Generated by Django 5.2.1 on 2025-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstock_trade', '0002_remove_trade_trade_type_trade_side_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.CharField(max_length=50, unique=True)),
                ('exchange_token', models.CharField(max_length=50)),
                ('trading_symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('instrument_type', models.CharField(max_length=50)),
                ('segment', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trading_symbol'],
                'indexes': [models.Index(fields=['trading_symbol'], name='mstock_trad_trading_519798_idx'), models.Index(fields=['instrument_token'], name='mstock_trad_instrum_f90d4c_idx'), models.Index(fields=['exchange'], name='mstock_trad_exchang_79eca2_idx')],
            },
        ),
    ]
