# Generated by Django 5.2 on 2025-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstock_trade', '0003_instrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='symbol',
            new_name='exchange',
        ),
        migrations.AddField(
            model_name='position',
            name='m2m',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='pnl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='product',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='realized_pnl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='trading_symbol',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='unrealized_pnl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='average_price',
            field=models.FloatField(),
        ),
    ]
