# Generated by Django 5.2 on 2025-05-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstock_trade', '0004_rename_symbol_position_exchange_position_m2m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
