# Generated by Django 5.2 on 2025-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstock_trade', '0005_remove_order_user_order_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='user',
        ),
        migrations.AddField(
            model_name='position',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
